import type { InvitationTemplate } from "./template-types";

export const banner2x1Template: InvitationTemplate = {
  id: "sunday-in-bloom-banner-2x1-v1",
  collectionSlug: "space-birthday",
  productCode: "banner-2x1",
  widthMm: 2000,
  heightMm: 1000,
  printProfile: {
    id: "banner-2x1-landscape",
    widthMm: 2000,
    heightMm: 1000,
    label: "Banner 2 x 1 m",
    instructionsKey: "large-format-banner",
    expectedPpi: 150,
  },
  widthPx: 11812,
  heightPx: 5906,
  master: {
    path: "space-birthday/invitation/BANNER 2mx1m-150.jpg",
    contentType: "image/jpeg",
  },
  preview: {
    src: "/momenta/space-birthday/banner/preview.webp",
    widthPx: 900,
  },
  artwork: {
    src: "/momenta/space-birthday/banner/preview.webp",
    contentType: "image/webp",
  },
  fields: {
    headline: {
      label: "Titulo",
      defaultValue: "WELCOME",
      x: 5906,
      y: 1380,
      width: 5200,
      fontFamily: "Arial, Helvetica, sans-serif",
      pdfFont: "helvetica",
      fontSize: 700,
      minFontSize: 360,
      fill: "#8e9678",
      align: "center",
      maxLines: 1,
    },
    monogram: {
      label: "Texto principal",
      defaultValue: "S & M",
      x: 6800,
      y: 2300,
      width: 3700,
      fontFamily: "Arial, Helvetica, sans-serif",
      pdfFont: "helvetica",
      fontSize: 640,
      minFontSize: 280,
      fill: "#8e9678",
      align: "center",
      maxLines: 1,
    },
    eventName: {
      label: "Subtitulo",
      defaultValue: "Anniversary",
      x: 7200,
      y: 2850,
      width: 2300,
      fontFamily: "Arial, Helvetica, sans-serif",
      pdfFont: "helvetica",
      fontSize: 210,
      minFontSize: 120,
      fill: "#9b9488",
      align: "center",
      maxLines: 1,
      letterSpacing: 18,
    },
  },
};
