import type { InvitationTemplate } from "./template-types";

const stickerCenters = [
  { x: 584, y: 850 },
  { x: 1754, y: 850 },
  { x: 2924, y: 850 },
  { x: 584, y: 2010 },
  { x: 1754, y: 2010 },
  { x: 2924, y: 2010 },
  { x: 584, y: 3160 },
  { x: 1754, y: 3160 },
  { x: 2924, y: 3160 },
  { x: 584, y: 4310 },
  { x: 1754, y: 4310 },
  { x: 2924, y: 4310 },
];

const pickCenters = (indexes: number[]) =>
  indexes.map((index) => stickerCenters[index]);

export const stickersA3Template: InvitationTemplate = {
  id: "sunday-in-bloom-stickers-a3-v1",
  collectionSlug: "space-birthday",
  productCode: "stickers-pack",
  widthMm: 297,
  heightMm: 420,
  widthPx: 3509,
  heightPx: 4961,
  master: {
    path: "space-birthday/invitation/STICKERS A3.jpg",
    contentType: "image/jpeg",
  },
  preview: {
    src: "/momenta/space-birthday/stickers/preview.webp",
    widthPx: 700,
  },
  artwork: {
    src: "/momenta/space-birthday/stickers/preview.webp",
    contentType: "image/webp",
  },
  fields: {
    monogram: {
      label: "Monograma",
      defaultValue: "S & M",
      x: stickerCenters[0].x,
      y: stickerCenters[0].y,
      copies: pickCenters([0, 5, 6, 11]).map((center) => ({
        x: center.x,
        y: center.y,
      })),
      width: 620,
      fontFamily: "Arial, Helvetica, sans-serif",
      pdfFont: "helvetica",
      fontSize: 138,
      minFontSize: 96,
      fill: "#ffffff",
      align: "center",
      maxLines: 1,
    },
    eventName: {
      label: "Subtitulo",
      defaultValue: "Anniversary",
      x: stickerCenters[0].x,
      y: stickerCenters[0].y + 90,
      copies: pickCenters([0, 5, 6, 11]).map((center) => ({
        x: center.x,
        y: center.y + 90,
      })),
      width: 520,
      fontFamily: "Arial, Helvetica, sans-serif",
      pdfFont: "helvetica",
      fontSize: 58,
      minFontSize: 40,
      fill: "#ffffff",
      align: "center",
      maxLines: 1,
    },
    ringText: {
      label: "Texto circular",
      defaultValue: "S&M - Anniversary",
      x: stickerCenters[1].x,
      y: stickerCenters[1].y,
      copies: pickCenters([0, 1, 4, 6, 7, 10]),
      width: 1050,
      fontFamily: "Arial, Helvetica, sans-serif",
      pdfFont: "helvetica",
      fontSize: 76,
      minFontSize: 54,
      fill: "#ffffff",
      align: "center",
      maxLines: 1,
      letterSpacing: 7,
      arc: {
        radius: 365,
        startAngle: 205,
        endAngle: 335,
      },
    },
    thanksText: {
      label: "Texto agradecimiento",
      defaultValue: "Thanks for coming",
      x: stickerCenters[2].x,
      y: stickerCenters[2].y,
      copies: pickCenters([2, 8]),
      width: 760,
      fontFamily: "Arial, Helvetica, sans-serif",
      pdfFont: "helvetica",
      fontSize: 60,
      minFontSize: 38,
      fill: "#9b9488",
      align: "center",
      maxLines: 1,
      letterSpacing: 5,
      arc: {
        radius: 350,
        startAngle: 205,
        endAngle: 335,
      },
    },
    leafText: {
      label: "Texto suave",
      defaultValue: "S&M - Anniversary",
      x: stickerCenters[9].x,
      y: stickerCenters[9].y,
      copies: pickCenters([9]),
      width: 800,
      fontFamily: "Arial, Helvetica, sans-serif",
      pdfFont: "helvetica",
      fontSize: 54,
      minFontSize: 34,
      fill: "#a7a195",
      align: "center",
      maxLines: 1,
      letterSpacing: 4,
      arc: {
        radius: 330,
        startAngle: 205,
        endAngle: 335,
      },
    },
  },
};
