export const validationEvents = [
  "home_viewed",
  "catalog_viewed",
  "category_viewed",
  "collection_viewed",
  "free_product_selected",
  "premium_product_viewed",
  "premium_details_viewed",
  "premium_preview_viewed",
  "premium_benefits_viewed",
  "premium_cta_clicked",
  "personalization_started",
  "personalization_step_viewed",
  "personalization_field_completed",
  "personalization_validation_failed",
  "personalization_back_clicked",
  "personalization_completed",
  "review_viewed",
  "personalization_edit_requested",
  "preview_requested",
  "preview_generation_started",
  "preview_generation_completed",
  "preview_generation_failed",
  "preview_viewed",
  "preview_edit_requested",
  "preview_confirmed",
  "download_page_viewed",
  "download_clicked",
  "download_simulated",
  "download_failed",
  "premium_upsell_viewed",
  "premium_upsell_clicked",
  "mock_checkout_started",
  "mock_checkout_viewed",
  "mock_checkout_cancelled",
  "purchase_intent_confirmed",
  "mock_checkout_completed",
  "premium_feedback_submitted",
] as const;

export type ValidationEventName = (typeof validationEvents)[number];
